In [2]:
%matplotlib inline

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

import statsmodels.formula.api as smf
import statsmodels



import pandas as pd
from sklearn.linear_model import LinearRegression
import statsmodels.api as sm

import numpy as np

import sklearn
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix

import matplotlib.pyplot as plt
import seaborn as sn

pd.set_option('display.max_rows', 300) # specifies number of rows to show
pd.options.display.float_format = '{:40,.4f}'.format # specifies default number format to 4 decimal places
plt.style.use('ggplot') # specifies that graphs should use ggplot styling
%matplotlib inline

import statsmodels
print(statsmodels.__version__)

print("pandas version: {}".format(pd.__version__))
print("statsmodels version: {}".format(statsmodels.__version__))

0.13.2
pandas version: 1.4.3
statsmodels version: 0.13.2

In [188]:
crime_bur = pd.read_csv('crime_burglary2011.csv')
edu2011 = pd.read_csv('education2011.csv')
age = pd.read_csv('Age.csv')
house_p = pd.read_csv('Median_houseP.csv')
BAME = pd.read_csv('BAME.csv')
household_indi = pd.read_csv('individual_household.csv')
income = pd.read_csv('median_income.csv')
car = pd.read_csv('car.csv')
household_income = pd.read_csv('household_income.csv')
population = pd.read_csv('population.csv')

In [189]:
#crime_edu = crime_bur.merge(edu2011, left_on='Row_Labels', right_on='mnemonic')

In [190]:
Bur_age = crime_bur.merge(age, left_on='Row_Labels', right_on='mnemonic')

In [191]:
crime_BAME = Bur_age.merge(BAME, left_on='Row_Labels', right_on='LSOAs')

In [192]:
crime_indi = crime_BAME.merge(household_indi, left_on='Row_Labels', right_on='LSOAs')

In [193]:
crime_income = crime_indi.merge(income, left_on='Row_Labels', right_on='Code')

In [194]:
crime_car = crime_income.merge(car, left_on='Row_Labels', right_on='LSOAs')

In [195]:
crime_household = crime_car.merge(household_income, left_on='Row_Labels', right_on='LSOAs')

/tmp/ipykernel_16797/3021212040.py:1: FutureWarning: Passing 'suffixes' which cause duplicate columns {'LSOAs_x'} in the result is deprecated and will raise a MergeError in a future version.
  crime_household = crime_car.merge(household_income, left_on='Row_Labels', right_on='LSOAs')

In [196]:
crime_pop = crime_household.merge(population, left_on='Row_Labels', right_on='LSOA')

In [145]:
'''
crime_hP = Bur_age.merge(house_p, left_on='Row_Labels', right_on='LSOAs')
'''

"\ncrime_hP = Bur_age.merge(house_p, left_on='Row_Labels', right_on='LSOAs')\n"

In [197]:
crime_pop

,Row_Labels,Burglary,Total_crime,2011 super output area - lower layer,mnemonic,Mean_Age,Median_Age,LSOAs_x,Ethnic_BAME,LSOAs_y,...,LSOAs_x,no_car,availability_of_all_cars,no_car_percent,car_per_household,LSOAs_y,Mean_year_household_income,Median_year_household_income,LSOA,Population
0,E01000006,18,98,Barking and Dagenham 016A,E01000006,32.4000,31.0000,E01000006,1146,E01000006,...,E01000006,186,496,34.3000,0.9000,E01000006,46141,39141,E01000006,1731
1,E01000007,13,372,Barking and Dagenham 015A,E01000007,28.4000,28.0000,E01000007,952,E01000007,...,E01000007,385,274,62.9000,0.4000,E01000007,30822,26229,E01000007,1417
2,E01000008,13,162,Barking and Dagenham 015B,E01000008,26.7000,26.0000,E01000008,1059,E01000008,...,E01000008,305,270,58.5000,0.5000,E01000008,28359,24204,E01000008,1569
3,E01000009,22,322,Barking and Dagenham 016B,E01000009,34.4000,31.0000,E01000009,1351,E01000009,...,E01000009,336,385,52.7000,0.6000,E01000009,38261,32464,E01000009,1798
4,E01000010,49,1077,Barking and Dagenham 015C,E01000010,27.7000,28.0000,E01000010,2028,E01000010,...,E01000010,818,324,74.2000,0.3000,E01000010,37277,31630,E01000010,2889
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4824,E01033742,5,57,Greenwich 007F,E01033742,29.6000,30.0000,E01033742,734,E01033742,...,E01033742,255,391,43.9000,0.7000,E01033742,48387,37255,E01033742,1365
4825,E01033743,6,261,Greenwich 002H,E01033743,26.6000,28.0000,E01033743,1445,E01033743,...,E01033743,254,522,38.3000,0.8000,E01033743,39272,30237,E01033743,2031
4826,E01033744,12,87,Greenwich 007G,E01033744,33.0000,31.0000,E01033744,964,E01033744,...,E01033744,301,434,46.6000,0.7000,E01033744,35936,27670,E01033744,1856
4827,E01033745,10,120,Greenwich 002I,E01033745,28.1000,29.0000,E01033745,1072,E01033745,...,E01033745,178,549,30.1000,0.9000,E01033745,40849,31450,E01033745,1816
4828,E01033746,20,82,Greenwich 038E,E01033746,39.9000,37.0000,E01033746,246,E01033746,...,E01033746,345,427,48.3000,0.6000,E01033746,64135,49381,E01033746,1470

In [180]:
'''
crime_housePrice = crime_housePri.rename(columns = {'Median Age':'age_median','Mean Age':'age_mean'})
print(crime_housePrice.columns)
'''

"\ncrime_housePrice = crime_housePri.rename(columns = {'Median Age':'age_median','Mean Age':'age_mean'})\nprint(crime_housePrice.columns)\n"

In [198]:

crime_pop_selected=crime_pop[['Burglary','Median_Age','Ethnic_BAME','individual_household',
                                 'Median_income','income_in_thou','no_car','availability_of_all_cars','no_car_percent',
                                'car_per_household','Mean_year_household_income','Median_year_household_income','Population']]

In [199]:
crime_pop_selected

,Burglary,Median_Age,Ethnic_BAME,individual_household,Median_income,income_in_thou,no_car,availability_of_all_cars,no_car_percent,car_per_household,Mean_year_household_income,Median_year_household_income,Population
0,18,31.0000,1146,17.9000,"36,300",36,186,496,34.3000,0.9000,46141,39141,1731
1,13,28.0000,952,41.3000,"31,230",31,385,274,62.9000,0.4000,30822,26229,1417
2,13,26.0000,1059,24.8000,"29,860",30,305,270,58.5000,0.5000,28359,24204,1569
3,22,31.0000,1351,29.9000,"33,550",34,336,385,52.7000,0.6000,38261,32464,1798
4,49,28.0000,2028,23.4000,"33,250",33,818,324,74.2000,0.3000,37277,31630,2889
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4824,5,30.0000,734,31.0000,"35,690",36,255,391,43.9000,0.7000,48387,37255,1365
4825,6,28.0000,1445,18.6000,"34,790",35,254,522,38.3000,0.8000,39272,30237,2031
4826,12,31.0000,964,26.2000,"31,580",32,301,434,46.6000,0.7000,35936,27670,1856
4827,10,29.0000,1072,17.6000,"35,260",35,178,549,30.1000,0.9000,40849,31450,1816
4828,20,37.0000,246,38.9000,"42,860",43,345,427,48.3000,0.6000,64135,49381,1470

In [200]:
crime_pop_selected.corr()

,Burglary,Median_Age,Ethnic_BAME,individual_household,income_in_thou,no_car,availability_of_all_cars,no_car_percent,car_per_household,Mean_year_household_income,Median_year_household_income,Population
Burglary,1.0000,-0.1400,0.1377,0.1329,0.0432,0.2508,-0.0313,0.1434,-0.1284,0.0425,0.0311,0.3039
Median_Age,-0.1400,1.0000,-0.5909,-0.1381,0.4375,-0.5600,0.7167,-0.6778,0.7137,0.3927,0.4397,-0.3576
Ethnic_BAME,0.1377,-0.5909,1.0000,-0.1899,-0.5704,0.2966,-0.3699,0.3552,-0.3322,-0.5249,-0.5441,0.5590
individual_household,0.1329,-0.1381,-0.1899,1.0000,0.0959,0.6909,-0.4133,0.6245,-0.6332,0.1053,0.0300,-0.0400
income_in_thou,0.0432,0.4375,-0.5704,0.0959,1.0000,-0.1798,0.3575,-0.3031,0.2924,0.9610,0.9604,-0.2036
no_car,0.2508,-0.5600,0.2966,0.6909,-0.1798,1.0000,-0.7135,0.9227,-0.8929,-0.1300,-0.2126,0.3928
availability_of_all_cars,-0.0313,0.7167,-0.3699,-0.4133,0.3575,-0.7135,1.0000,-0.9012,0.8921,0.2930,0.3659,0.0625
no_car_percent,0.1434,-0.6778,0.3552,0.6245,-0.3031,0.9227,-0.9012,1.0000,-0.9687,-0.2413,-0.3256,0.1871
car_per_household,-0.1284,0.7137,-0.3322,-0.6332,0.2924,-0.8929,0.8921,-0.9687,1.0000,0.2372,0.3191,-0.2023
Mean_year_household_income,0.0425,0.3927,-0.5249,0.1053,0.9610,-0.1300,0.2930,-0.2413,0.2372,1.0000,0.9846,-0.1953
Median_year_household_income,0.0311,0.4397,-0.5441,0.0300,0.9604,-0.2126,0.3659,-0.3256,0.3191,0.9846,1.0000,-0.2036
Population,0.3039,-0.3576,0.5590,-0.0400,-0.2036,0.3928,0.0625,0.1871,-0.2023,-0.1953,-0.2036,1.0000

In [201]:
LR_crime_pop_selected = sm.formula.ols('Burglary ~ Ethnic_BAME + Median_Age + income_in_thou + individual_household + no_car + Mean_year_household_income + Population', 
                                       data=crime_pop_selected).fit()
LR_crime_pop_selected.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:               Burglary   R-squared:                       0.130
Model:                            OLS   Adj. R-squared:                  0.129
Method:                 Least Squares   F-statistic:                     102.9
Date:                Sun, 15 Jan 2023   Prob (F-statistic):          9.74e-141
Time:                        23:06:19   Log-Likelihood:                -18571.
No. Observations:                4829   AIC:                         3.716e+04
Df Residuals:                    4821   BIC:                         3.721e+04
Df Model:                           7
Covariance Type:            nonrobust
==============================================================================================
                                 coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------------
Intercept                    -16.5673      2.807     -5.901      0.000     -22.071     -11.064
Ethnic_BAME                    0.0013      0.001      1.953      0.051   -5.28e-06       0.003
Median_Age                    -0.0243      0.050     -0.484      0.628      -0.123       0.074
income_in_thou                 0.3970      0.093      4.250      0.000       0.214       0.580
individual_household           0.0703      0.033      2.157      0.031       0.006       0.134
no_car                         0.0094      0.002      4.339      0.000       0.005       0.014
Mean_year_household_income  -6.23e-05   3.77e-05     -1.652      0.099      -0.000    1.16e-05
Population                     0.0118      0.001     14.232      0.000       0.010       0.013
==============================================================================
Omnibus:                     4406.656   Durbin-Watson:                   1.437
Prob(Omnibus):                  0.000   Jarque-Bera (JB):           549614.595
Skew:                           3.895   Prob(JB):                         0.00
Kurtosis:                      54.681   Cond. No.                     8.43e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 8.43e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""